"""fix_updated_at_default_value

Revision ID: f82923a1ca06
Revises: a00aa7b497bf
Create Date: 2025-06-07 13:08:01.405804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82923a1ca06'
down_revision: Union[str, None] = 'a00aa7b497bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
